export const SILK_ROAD_ARTICLES = [
  {
    id: 'ai-za-malak-biznes',
    title: 'AI за малкия бизнес: 5 приложения, ограничения и първи стъпки',
    seoTitle: 'AI за малкия бизнес: приложения и първи стъпки | TAVORA',
    description: 'Започни с една проверима задача. Виж пет приложения на AI, пример с клиентски отговор и как да сравниш черновата с условията на услугата.',
    category: 'AI & Бизнес',
    categoryColor: 'bg-violet-50 text-violet-700',
    readTime: '6 мин.',
    keywords: ['AI за малкия бизнес', 'изкуствен интелект за бизнес', 'AI приложения'],
    ctaText: 'В безплатния модул 01 на „Пътят на коприната“ упражняваш ясна задача, избор на AI и проверка на резултата. Пълните уроци се отварят през акаунт.',
    ctaPrimaryTo: '/module/s01-m01?lesson=0',
    ctaPrimaryLabel: 'Модул 01 — с акаунт',
    related: ['koga-avtomatizaciyata-si-struva', 'sait-s-ai-kakvo-da-proverish'],
  },
  {
    id: 'sait-s-ai-kakvo-da-proverish',
    title: 'Създаване на сайт с AI: 9 проверки преди публикуване',
    seoTitle: 'Създаване на сайт с AI: 9 проверки преди публикуване | TAVORA',
    description: 'AI генерира страница, но работи ли тя за посетителя? Провери предложението, телефона, формата, грешките, достъпа и получаването на запитването.',
    category: 'Уеб дизайн',
    categoryColor: 'bg-teal-50 text-teal-700',
    readTime: '6 мин.',
    keywords: ['създаване на сайт с AI', 'сайт с изкуствен интелект', 'проверка на сайт'],
    ctaText: 'Опитай публичния учебен прототип без покупка. В модулите 02, 06, 07 и 08 свързваш страницата с предложение, действие, собственост и ограничен достъп.',
    ctaPrimaryTo: '/academy-labs/silk-road/start',
    ctaPrimaryLabel: 'Опитай учебния прототип',
    related: ['sait-poseshteniya-bez-zapitvaniya', 'seo-za-nachinaeshti'],
  },
  {
    id: 'sait-poseshteniya-bez-zapitvaniya',
    title: 'Сайт с посещения, но без запитвания: 7 проверки преди още реклама',
    seoTitle: 'Сайт с посещения, но без запитвания: 7 проверки | TAVORA',
    description: 'Проследи пътя от посещението до получената заявка. Различи неподходящ трафик, неясна услуга и счупена форма с конкретна проверка на всяка стъпка.',
    category: 'Маркетинг',
    categoryColor: 'bg-amber-50 text-amber-700',
    readTime: '6 мин.',
    keywords: ['сайт без запитвания', 'посещения без клиенти', 'конверсии на сайт'],
    ctaText: '„Пътят на коприната“ свързва структурата на страницата, аудиторията и изпълненото действие. Първо можеш да провериш малък учебен прототип без покупка.',
    ctaPrimaryTo: '/academy-labs/silk-road/start',
    ctaPrimaryLabel: 'Провери учебен прототип',
    related: ['sait-s-ai-kakvo-da-proverish', 'ga4-realni-zapitvaniya-pokupki'],
  },
  {
    id: 'seo-za-nachinaeshti',
    title: 'SEO за начинаещи: как Google открива, индексира и класира сайта',
    seoTitle: 'SEO за начинаещи: откриване, индексиране, класиране | TAVORA',
    description: 'Разбери разликата между обход, индекс и позиция. Провери един адрес, sitemap, заглавието и вътрешните връзки по официалните указания на Google.',
    category: 'SEO',
    categoryColor: 'bg-emerald-50 text-emerald-700',
    readTime: '6 мин.',
    keywords: ['SEO за начинаещи', 'индексиране в Google', 'sitemap'],
    ctaText: 'Модул 03 в „Пътят на коприната“ свързва човешките въпроси, достъпната страница и проверката на видимостта. Началният модул 01 е безплатен през акаунт.',
    ctaPrimaryTo: '/kurs/ai-business-blueprint',
    ctaPrimaryLabel: 'Виж програмата',
    related: ['seo-geo-razlika', 'sait-s-ai-kakvo-da-proverish'],
  },
  {
    id: 'seo-geo-razlika',
    title: 'SEO и GEO: разлики и проверка на видимостта в Google и AI',
    seoTitle: 'SEO и GEO: разлики и проверка на AI видимостта | TAVORA',
    description: 'Позиция в Google, споменаване от AI, цитирана страница и посещение са различни резултати. Виж как да ги провериш и какво Google изисква за AI функциите.',
    category: 'GEO & AI',
    categoryColor: 'bg-indigo-50 text-indigo-700',
    readTime: '6 мин.',
    keywords: ['SEO и GEO', 'GEO оптимизация', 'AI видимост'],
    ctaText: 'В модул 03 упражняваш SEO и GEO върху конкретна страница и отделяш наблюдаваното от предположението. Виж обхвата на програмата и безплатното начало.',
    ctaPrimaryTo: '/kurs/ai-business-blueprint',
    ctaPrimaryLabel: 'Виж програмата',
    related: ['seo-za-nachinaeshti', 'ga4-realni-zapitvaniya-pokupki'],
  },
  {
    id: 'ga4-realni-zapitvaniya-pokupki',
    title: 'GA4 конверсии: как да измерваш реални запитвания и покупки',
    seoTitle: 'GA4 конверсии: реални запитвания и покупки | TAVORA',
    description: 'Различи събитие, ключово събитие и конверсия. Свери клик, приета форма, потвърдено плащане и предоставен достъп с учебна таблица и проверки за повторения.',
    category: 'Измерване',
    categoryColor: 'bg-sky-50 text-sky-700',
    readTime: '6 мин.',
    keywords: ['GA4 конверсии', 'ключови събития GA4', 'проследяване на покупки'],
    ctaText: 'Модул 09 е за измерване и решения, а модул 06 — за пътя до получена услуга. „Пътят на коприната“ упражнява тези връзки; не е специализиран курс по напреднал GA4.',
    ctaPrimaryTo: '/kurs/ai-business-blueprint',
    ctaPrimaryLabel: 'Виж програмата',
    related: ['sait-poseshteniya-bez-zapitvaniya', 'koga-avtomatizaciyata-si-struva'],
  },
  {
    id: 'koga-avtomatizaciyata-si-struva',
    title: 'AI автоматизация: кога си струва и как да сметнеш разхода',
    seoTitle: 'AI автоматизация: разход и кога се изплаща | TAVORA',
    description: 'Сметни времето след проверките и поправките, инструментите и поддръжката. Два учебни сценария показват кога автоматизацията има смисъл и кога да я отложиш.',
    category: 'AI & Бизнес',
    categoryColor: 'bg-violet-50 text-violet-700',
    readTime: '6 мин.',
    keywords: ['AI автоматизация', 'разход за автоматизация', 'възвръщаемост автоматизация'],
    ctaText: 'Модул 10 в „Пътят на коприната“ упражнява малък процес с ясни правила, откази и повторения. Курсът не се представя като специализирано обучение по n8n.',
    ctaPrimaryTo: '/kurs/ai-business-blueprint',
    ctaPrimaryLabel: 'Виж програмата',
    related: ['ai-za-malak-biznes', 'cena-na-digitalna-usluga'],
  },
  {
    id: 'cena-na-digitalna-usluga',
    title: 'Ценообразуване за фрийлансъри: как да сметнеш цена на дигитална услуга',
    seoTitle: 'Цена на дигитална услуга: ставка и проектна оферта | TAVORA',
    description: 'Изчисли разхода, платимите часове и проектната цена. Сравни две оферти за 600 € с различен обхват, корекции и поддръжка, без измислени пазарни ставки.',
    category: 'Бизнес',
    categoryColor: 'bg-orange-50 text-orange-700',
    readTime: '6 мин.',
    keywords: ['ценообразуване за фрийлансъри', 'цена на дигитална услуга', 'часова ставка'],
    ctaText: 'Модул 11 за услуга, цена и устойчиво изпълнение е в пълната програма на „Пътят на коприната“. Виж пакетите и обхвата; обучението не обещава гарантирани клиенти или печалба.',
    ctaPrimaryTo: '/kurs/ai-business-blueprint',
    ctaPrimaryLabel: 'Виж пълната програма',
    related: ['koga-avtomatizaciyata-si-struva', 'sait-poseshteniya-bez-zapitvaniya'],
  },
] as const;

export type SilkRoadArticleId = typeof SILK_ROAD_ARTICLES[number]['id'];

export function getSilkRoadArticle(id: SilkRoadArticleId) {
  return SILK_ROAD_ARTICLES.find(article => article.id === id)!;
}
