"""Generate the compatible release into an existing CLI-created migration file."""
import argparse
import json
import re
from pathlib import Path
from perfect_video_start_content import BASE_RELEASE, BLOCKS, LESSONS, RELEASE, SHUTTER_NEW, SHUTTER_OLD

ROOT = Path(__file__).resolve().parents[2]
BASE_FILE = ROOT / "supabase/migrations/20260928104816_perfect_video_modules_1_3_curriculum_v4_2_drafts.sql"
PROGRESS_FILE = ROOT / "supabase/migrations/20261001175901_academy_retire_open_answers.sql"

def progress_guard():
    definition = re.search(r"CREATE OR REPLACE FUNCTION academy_private\.refresh_lesson_progress\(.*?END \$function\$;", PROGRESS_FILE.read_text(), re.S)[0]
    body = definition.split("$function$")[1]
    marker = "  SELECT count(*) FILTER (WHERE required AND block_type NOT IN"
    assert body.count(marker) == 1
    keys = ",".join("'" + item["key"] + "'" for item in BLOCKS if "evaluation" in item)
    guard = f"""  -- The new zero-XP checks record attempts and their own completion, not a new
  -- grade, mastery, XP, PDF completion or badge for the old lesson.
  IF EXISTS (
    SELECT 1 FROM public.academy_lessons l
    JOIN public.academy_lesson_blocks b ON b.version_id=l.published_version_id
    WHERE l.id=p_lesson AND l.module_id IN ('s02-m01','s02-m02','s02-m03')
      AND p.version_id=l.published_version_id AND b.block_key=p.current_block_key
      AND b.block_key=ANY(ARRAY[{keys}])
      AND NOT b.required AND b.points=0
      AND b.block_type IN ('matching','scenario','calculator')
  ) THEN RETURN to_jsonb(p); END IF;

"""
    return body, definition.replace(marker, guard + marker)

def encoded(value):
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))

def base_specs():
    return json.loads(re.search(r"\$pv_v42_payload\$(.*?)\$pv_v42_payload\$", BASE_FILE.read_text(), re.S)[1])

def replacements():
    specs = base_specs()
    assert len(specs) == len(LESSONS) == 65
    output = []
    for row in specs:
        lesson = row["lesson_id"]
        intro, task, check = LESSONS[lesson]
        blocks = {b["key"]: b for b in row["blocks"]}
        boundary = blocks["field_note"]["content"]["body"].split("\n\nКарта за работа")[0]
        output.append(dict(lesson=lesson,module=row["module_id"],intro=intro,
            objective=dict(body=intro,deliverable=task,check=check),
            note=dict(body=f"{task}\n\nСамопроверка: {check}\n\nГраница: {boundary}\n\nУчебната папка и първият клип са на /academy-labs/perfect-video/start. Можеш да използваш предоставения случай, без да търсиш клиент или оценител."),
            before={key:blocks[key]["content"] for key in ["objective","field_note"]}))
    return output

def build_sql():
    refresh_before, refresh_after = progress_guard()
    tables = ["public.academy_lesson_progress","public.academy_lesson_attempts_v2","academy_private.lesson_progress_history","public.pdf_progress","public.profiles","public.academy_access_grants","public.academy_user_badges"]
    fingerprint = "jsonb_build_object(" + ",".join(f"'{t}',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(jsonb_agg(to_jsonb(x) ORDER BY to_jsonb(x)::text),'[]'::jsonb)::text)) FROM {t} x)" for t in tables) + ")"
    sql = r'''-- Generated by scripts/perfect-video/build_perfect_video_start.py.
-- 65 authored openings and tasks; original theory and grading identities preserved.
-- Added checks are optional with zero XP; original attempts and resume state are not rewritten.
-- The narrowly scoped refresh guard prevents a new optional attempt from rewriting old aggregates.
SET lock_timeout='5s';
DO $video_results$
DECLARE
 specs jsonb := $pv_results_payload$__SPECS__$pv_results_payload$::jsonb;
 additions jsonb := $pv_results_additions$__ADDITIONS__$pv_results_additions$::jsonb;
 release_name text := '__RELEASE__';
 spec jsonb; addition jsonb; lesson_row public.academy_lessons; version_row public.academy_lesson_versions;
 block_row public.academy_lesson_blocks; key_row academy_private.lesson_block_keys;
 learner_before jsonb; identities_before text; grade_before jsonb; grade_after jsonb;
 old_ids uuid[]; new_id uuid; next_position integer; snapshot jsonb; validation_result jsonb;
 already integer; eligible integer;
 refresh_before text; refresh_definition text;
BEGIN
 LOCK TABLE public.academy_lessons,public.academy_lesson_versions,public.academy_lesson_blocks,
 academy_private.lesson_block_keys,__TABLES__ IN SHARE ROW EXCLUSIVE MODE;
 SELECT count(*) INTO already FROM public.academy_lessons l
 WHERE l.module_id IN ('s02-m01','s02-m02','s02-m03') AND EXISTS(
  SELECT 1 FROM public.academy_lesson_audit a WHERE a.academy_lesson_id=l.id
   AND a.version_id=l.published_version_id AND a.details->>'release'=release_name);
 IF already=65 THEN RETURN; END IF;
 IF already<>0 THEN RAISE EXCEPTION 'Partial video results release; stop and inspect'; END IF;
 SELECT count(*) INTO eligible FROM public.academy_lessons l JOIN public.academy_lesson_versions v ON v.id=l.published_version_id
 WHERE l.module_id IN ('s02-m01','s02-m02','s02-m03') AND l.status='published'
  AND l.published_version_id=l.draft_version_id AND v.change_note='__BASE__';
 IF eligible=0 THEN RAISE NOTICE 'Video v4.2 base absent; results migration skipped'; RETURN; END IF;
 IF eligible<>65 THEN RAISE EXCEPTION 'Expected 65 video base lessons, found %',eligible; END IF;
 learner_before:=__FINGERPRINT__;
 SELECT md5(jsonb_agg(jsonb_build_object('id',l.id,'module',l.module_id,'lesson',l.lesson_id,'status',l.status,'published',l.published_version_id,'draft',l.draft_version_id,'number',v.version_number) ORDER BY l.id)::text)
 INTO identities_before FROM public.academy_lessons l LEFT JOIN public.academy_lesson_versions v ON v.id=l.published_version_id;
 SELECT p.prosrc,pg_get_functiondef(p.oid) INTO refresh_before,refresh_definition
 FROM pg_proc p WHERE p.oid='academy_private.refresh_lesson_progress(uuid,uuid)'::regprocedure;
 IF btrim(refresh_before,E' \t\n\r') IS DISTINCT FROM btrim($pv_refresh_expected$__REFRESH_BEFORE__$pv_refresh_expected$,E' \t\n\r') THEN
  RAISE EXCEPTION 'Video progress function drift; stop and inspect';
 END IF;

 FOR spec IN SELECT value FROM jsonb_array_elements(specs) LOOP
  SELECT * INTO STRICT lesson_row FROM public.academy_lessons WHERE module_id=spec->>'module' AND lesson_id=spec->>'lesson' FOR UPDATE;
  SELECT * INTO STRICT version_row FROM public.academy_lesson_versions WHERE id=lesson_row.published_version_id FOR UPDATE;
  IF EXISTS(SELECT 1 FROM jsonb_each(spec->'before') e WHERE NOT EXISTS(
    SELECT 1 FROM public.academy_lesson_blocks b WHERE b.version_id=version_row.id AND b.block_key=e.key AND b.content=e.value))
   OR (SELECT count(*) FROM public.academy_lesson_blocks WHERE version_id=version_row.id)<>15 THEN
   RAISE EXCEPTION 'Video source drift for %',lesson_row.lesson_id;
  END IF;
  SELECT array_agg(b.id ORDER BY b.position),
   jsonb_build_object('version',to_jsonb(version_row),'blocks',jsonb_agg(to_jsonb(b)||jsonb_build_object('evaluation',coalesce(k.answer_key,'{}'),'feedback',coalesce(k.feedback,'{}'),'scoring',coalesce(k.scoring,'{}')) ORDER BY b.position)),
   jsonb_agg(jsonb_build_object('id',b.id,'key',b.block_key,'type',b.block_type,'required',b.required,'points',b.points,'answer',k.answer_key,'scoring',k.scoring,
    'graded_content',CASE WHEN b.block_type IN ('quiz','scenario','sequence_sort','matching','calculator','client_simulation','decision_tree','image_hotspot','course_exam') THEN b.content ELSE NULL END,
    'feedback',CASE WHEN lesson_row.lesson_id='pv03-02' AND b.block_key='knowledge_check' THEN k.feedback-'explanation' ELSE k.feedback END) ORDER BY b.id)
  INTO old_ids,snapshot,grade_before FROM public.academy_lesson_blocks b LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id WHERE b.version_id=version_row.id;
  INSERT INTO public.academy_lesson_audit(academy_lesson_id,version_id,action,details)
  VALUES(lesson_row.id,version_row.id,'saved',jsonb_build_object('release',release_name,'mode','compatible_results_supplement','before',snapshot,'progress_unchanged',true,'new_checks_optional',true)
   || CASE WHEN lesson_row.lesson_id='pv01-01' THEN jsonb_build_object('before_refresh_function',refresh_definition) ELSE '{}'::jsonb END);
  UPDATE public.academy_lesson_blocks SET content=spec->'objective' WHERE version_id=version_row.id AND block_key='objective';
  UPDATE public.academy_lesson_blocks SET content=spec->'note' WHERE version_id=version_row.id AND block_key='field_note';

  IF lesson_row.lesson_id='pv03-02' THEN
   SELECT * INTO STRICT block_row FROM public.academy_lesson_blocks WHERE version_id=version_row.id AND block_key='core';
   IF position('__SHUTTER_OLD__' in block_row.content->>'body')=0 THEN RAISE EXCEPTION 'Shutter source drift'; END IF;
   UPDATE public.academy_lesson_blocks SET content=jsonb_set(content,'{body}',to_jsonb(replace(content->>'body','__SHUTTER_OLD__','__SHUTTER_NEW__'))) WHERE id=block_row.id;
   SELECT * INTO STRICT block_row FROM public.academy_lesson_blocks WHERE version_id=version_row.id AND block_key='summary';
   IF position('__SHUTTER_OLD__' in block_row.content#>>'{takeaways,0}')=0 THEN RAISE EXCEPTION 'Shutter summary drift'; END IF;
   UPDATE public.academy_lesson_blocks SET content=jsonb_set(content,'{takeaways,0}',to_jsonb(replace(content#>>'{takeaways,0}','__SHUTTER_OLD__','__SHUTTER_NEW__'))) WHERE id=block_row.id;
   SELECT * INTO STRICT block_row FROM public.academy_lesson_blocks WHERE version_id=version_row.id AND block_key='knowledge_check';
   SELECT * INTO STRICT key_row FROM academy_private.lesson_block_keys WHERE block_id=block_row.id;
   IF position('__SHUTTER_OLD__' in key_row.feedback->>'explanation')=0 THEN RAISE EXCEPTION 'Shutter feedback drift'; END IF;
   UPDATE academy_private.lesson_block_keys SET feedback=jsonb_set(feedback,'{explanation}',to_jsonb(replace(feedback->>'explanation','__SHUTTER_OLD__','__SHUTTER_NEW__'))) WHERE block_id=block_row.id;
  END IF;

  SELECT coalesce(max(position),0)+1 INTO next_position FROM public.academy_lesson_blocks WHERE version_id=version_row.id;
  FOR addition IN SELECT value FROM jsonb_array_elements(additions) WHERE value->>'lesson'=lesson_row.lesson_id LOOP
   INSERT INTO public.academy_lesson_blocks(version_id,block_key,position,block_type,title,content,required,points)
   VALUES(version_row.id,addition->>'key',next_position,addition->>'type',addition->>'title',addition->'content',false,0) RETURNING id INTO new_id;
   next_position:=next_position+1;
   IF addition?'evaluation' THEN
    INSERT INTO academy_private.lesson_block_keys(block_id,answer_key,feedback,scoring) VALUES(new_id,addition->'evaluation',addition->'feedback','{}');
   END IF;
  END LOOP;
  SELECT jsonb_agg(jsonb_build_object('id',b.id,'key',b.block_key,'type',b.block_type,'required',b.required,'points',b.points,'answer',k.answer_key,'scoring',k.scoring,
   'graded_content',CASE WHEN b.block_type IN ('quiz','scenario','sequence_sort','matching','calculator','client_simulation','decision_tree','image_hotspot','course_exam') THEN b.content ELSE NULL END,
   'feedback',CASE WHEN lesson_row.lesson_id='pv03-02' AND b.block_key='knowledge_check' THEN k.feedback-'explanation' ELSE k.feedback END) ORDER BY b.id)
  INTO grade_after FROM public.academy_lesson_blocks b LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id WHERE b.id=ANY(old_ids);
  IF grade_before IS DISTINCT FROM grade_after THEN RAISE EXCEPTION 'Existing video grading changed for %',lesson_row.lesson_id; END IF;
  IF EXISTS(SELECT 1 FROM public.academy_lesson_blocks WHERE version_id=version_row.id AND NOT(id=ANY(old_ids)) AND (required OR points<>0)) THEN RAISE EXCEPTION 'New activity changed video completion or XP'; END IF;
  validation_result:=academy_private.lesson_validation(version_row.id);
  IF jsonb_array_length(validation_result->'errors')>0 THEN RAISE EXCEPTION 'Invalid video lesson %: %',lesson_row.lesson_id,validation_result; END IF;
  UPDATE public.academy_lesson_versions SET objective=spec->>'intro',change_note=release_name,validation=validation_result WHERE id=version_row.id;
 END LOOP;
 EXECUTE $pv_refresh_definition$__REFRESH_AFTER__$pv_refresh_definition$;

 IF learner_before IS DISTINCT FROM __FINGERPRINT__ THEN RAISE EXCEPTION 'Learner records changed; abort video results release'; END IF;
 IF identities_before IS DISTINCT FROM (SELECT md5(jsonb_agg(jsonb_build_object('id',l.id,'module',l.module_id,'lesson',l.lesson_id,'status',l.status,'published',l.published_version_id,'draft',l.draft_version_id,'number',v.version_number) ORDER BY l.id)::text) FROM public.academy_lessons l LEFT JOIN public.academy_lesson_versions v ON v.id=l.published_version_id) THEN RAISE EXCEPTION 'Published lesson identity changed'; END IF;
 IF (SELECT count(*) FROM public.academy_lesson_blocks b JOIN public.academy_lessons l ON l.published_version_id=b.version_id WHERE l.module_id IN ('s02-m01','s02-m02','s02-m03') AND b.block_key LIKE 'checkpoint_video_%_20261003')<>10 THEN RAISE EXCEPTION 'Missing video checkpoints'; END IF;
 UPDATE public.academy_lesson_audit SET details=details||jsonb_build_object('publication_receipt',jsonb_build_object('release',release_name,'published_lessons',65,'optional_blocks',jsonb_array_length(additions),'independent_checks',10,'applied_at',clock_timestamp(),'learner_records_unchanged',true,'lesson_identity_unchanged',true,'correct_answers_unchanged',true,'checked_tables',learner_before))
 WHERE version_id=(SELECT published_version_id FROM public.academy_lessons WHERE module_id='s02-m01' AND lesson_id='pv01-01') AND details->>'release'=release_name;
END $video_results$;
'''
    replace = {"__SPECS__":encoded(replacements()),"__ADDITIONS__":encoded(BLOCKS),"__RELEASE__":RELEASE,
        "__BASE__":BASE_RELEASE,"__SHUTTER_OLD__":SHUTTER_OLD,"__SHUTTER_NEW__":SHUTTER_NEW,
        "__TABLES__":",".join(tables),"__FINGERPRINT__":fingerprint,"__REFRESH_BEFORE__":refresh_before,"__REFRESH_AFTER__":refresh_after}
    for key,value in replace.items():
        sql=sql.replace(key,value)
    assert "__" not in sql
    return sql

if __name__ == "__main__":
    parser=argparse.ArgumentParser()
    parser.add_argument("--migration",type=Path,required=True)
    args=parser.parse_args()
    if not args.migration.exists():
        raise SystemExit("Create the file with supabase migration new first.")
    args.migration.write_text(build_sql(),encoding="utf-8")
    print(f"65 compatible lessons; {len(BLOCKS)} optional additions; 10 separate checks.")
