"""Package the approved modules 4–6 editorial release without rewriting it."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PAYLOAD = ROOT / "scripts/perfect-video/releases/modules-4-6-clear-practice-20261004.json"
MIGRATION = ROOT / "supabase/migrations/20261004073713_perfect_video_modules_4_6_clear_practice.sql"
RELEASE = "perfect_video_modules_4_6_clear_practice_20261004"
TABLES = [
    "public.academy_lesson_progress",
    "public.academy_lesson_attempts_v2",
    "academy_private.lesson_progress_history",
    "public.pdf_progress",
    "public.profiles",
    "public.academy_access_grants",
    "public.academy_user_badges",
]


def learner_fingerprint():
    parts = []
    for table in TABLES:
        parts.append(
            f"'{table}',(SELECT jsonb_build_object('rows',count(*),'hash',"
            "md5(coalesce(jsonb_agg(to_jsonb(x) ORDER BY to_jsonb(x)::text),'[]'::jsonb)::text)) "
            f"FROM {table} x)"
        )
    return "jsonb_build_object(" + ",\n  ".join(parts) + ")"


def build():
    specs = json.loads(PAYLOAD.read_text())
    assert len(specs) == 43 and len({s["lesson"] for s in specs}) == 43
    assert {m: sum(s["module"] == m for s in specs) for m in ("s02-m04", "s02-m05", "s02-m06")} == {
        "s02-m04": 17, "s02-m05": 8, "s02-m06": 18,
    }
    assert all(len(s["blocks"]) == 15 for s in specs)
    assert sum("evaluation" in b for s in specs for b in s["blocks"]) == 215
    assert all(len(s["source_hash"]) == 32 for s in specs)
    for s in specs:
        assert sorted(b["position"] for b in s["blocks"]) == list(range(15))
        assert len({b["key"] for b in s["blocks"]}) == 15
        for b in s["blocks"]:
            assert not {"evaluation", "answer_key", "scoring", "feedback"}.intersection(b["content"])
            if "evaluation" in b:
                assert b["feedback"]["explanation"].strip()
    payload = json.dumps(specs, ensure_ascii=False, separators=(",", ":"))
    assert "$pv456_payload$" not in payload
    identity = """(SELECT md5(coalesce(jsonb_agg(jsonb_build_object(
  'lesson',to_jsonb(l),'version_id',v.id,'number',v.version_number,
  'title',v.title,'subtitle',v.subtitle,'duration',v.duration,'estimated_minutes',v.estimated_minutes,
  'source_kind',v.source_kind,'origin',v.origin_version_id) ORDER BY l.id),'[]'::jsonb)::text)
  FROM public.academy_lessons l LEFT JOIN public.academy_lesson_versions v ON v.id=l.published_version_id)"""
    grading = """(SELECT md5(coalesce(jsonb_agg(jsonb_build_object(
  'block',to_jsonb(b)-'title'-'content'-'updated_at',
  'private_key',to_jsonb(k)-'feedback'-'updated_at') ORDER BY b.id),'[]'::jsonb)::text)
  FROM public.academy_lesson_blocks b LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id)"""
    sql = f"""-- Generated by scripts/perfect-video/build_perfect_video_456_clear_practice.py.
-- Publishes the approved 43 lesson drafts; no additional teaching edits.
-- Same lesson/version/block IDs, grading identities, requirements, XP and learner rows.
-- Complete prior content is archived in the existing protected editorial audit.
DO $pv456_release$
DECLARE
 release_name text := '{RELEASE}';
 specs jsonb := $pv456_payload${payload}$pv456_payload$::jsonb;
 spec jsonb; block_spec jsonb;
 lesson_row public.academy_lessons; version_row public.academy_lesson_versions;
 block_row public.academy_lesson_blocks; key_row academy_private.lesson_block_keys;
 catalog_count integer; already integer; source_hash text; snapshot jsonb;
 learner_before jsonb; identities_before text; grading_before text; validation_result jsonb;
BEGIN
 PERFORM set_config('lock_timeout','5s',true);
 LOCK TABLE public.academy_lessons,public.academy_lesson_versions,public.academy_lesson_blocks,
 academy_private.lesson_block_keys,public.academy_lesson_audit,
 {','.join(TABLES)} IN SHARE ROW EXCLUSIVE MODE;

 SELECT count(*) INTO catalog_count FROM public.academy_lessons
 WHERE module_id IN ('s02-m04','s02-m05','s02-m06');
 IF catalog_count=0 THEN RAISE NOTICE 'Video modules 4–6 base absent; editorial release skipped'; RETURN; END IF;
 IF catalog_count<>43 THEN RAISE EXCEPTION 'Expected 43 video lessons, found %',catalog_count; END IF;
 SELECT count(*) INTO already FROM public.academy_lessons l
 WHERE l.module_id IN ('s02-m04','s02-m05','s02-m06') AND EXISTS(
  SELECT 1 FROM public.academy_lesson_audit a WHERE a.academy_lesson_id=l.id
  AND a.version_id=l.published_version_id AND a.details->>'release'=release_name);
 IF already=43 THEN RETURN; END IF;
 IF already<>0 THEN RAISE EXCEPTION 'Partial video modules 4–6 archive; stop and inspect'; END IF;
 learner_before:={learner_fingerprint()};
 identities_before:={identity};
 grading_before:={grading};

 FOR spec IN SELECT value FROM jsonb_array_elements(specs) LOOP
  SELECT * INTO STRICT lesson_row FROM public.academy_lessons
  WHERE module_id=spec->>'module' AND lesson_id=spec->>'lesson' FOR UPDATE;
  IF lesson_row.status<>'published' OR lesson_row.published_version_id IS NULL
   OR lesson_row.published_version_id IS DISTINCT FROM lesson_row.draft_version_id THEN
   RAISE EXCEPTION 'Video publication state changed for %',lesson_row.lesson_id;
  END IF;
  SELECT * INTO STRICT version_row FROM public.academy_lesson_versions
  WHERE id=lesson_row.published_version_id FOR UPDATE;
  IF version_row.version_number<>3 THEN RAISE EXCEPTION 'Video version changed for %',lesson_row.lesson_id; END IF;
  SELECT md5(jsonb_build_object(
   'title',version_row.title,'subtitle',version_row.subtitle,'duration',version_row.duration,
   'objective',version_row.objective,'hook',version_row.hook,
   'estimated_minutes',version_row.estimated_minutes,'change_note',version_row.change_note,
   'blocks',jsonb_agg(jsonb_build_object(
    'block_key',b.block_key,'position',b.position,'block_type',b.block_type,'title',b.title,
    'content',b.content,'required',b.required,'points',b.points,
    'evaluation',coalesce(k.answer_key,'{{}}'::jsonb),
    'feedback',coalesce(k.feedback,'{{}}'::jsonb),
    'scoring',coalesce(k.scoring,'{{}}'::jsonb)) ORDER BY b.position))::text)
  INTO source_hash FROM public.academy_lesson_blocks b
  LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id WHERE b.version_id=version_row.id;
  IF source_hash IS DISTINCT FROM spec->>'source_hash' THEN
   RAISE EXCEPTION 'Video source drift for %',lesson_row.lesson_id;
  END IF;
  SELECT jsonb_build_object('version',to_jsonb(version_row),'blocks',jsonb_agg(
   to_jsonb(b)||jsonb_build_object('evaluation',coalesce(k.answer_key,'{{}}'::jsonb),
    'feedback',coalesce(k.feedback,'{{}}'::jsonb),'scoring',coalesce(k.scoring,'{{}}'::jsonb)) ORDER BY b.position))
  INTO snapshot FROM public.academy_lesson_blocks b
  LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id WHERE b.version_id=version_row.id;
  INSERT INTO public.academy_lesson_audit(academy_lesson_id,version_id,action,details)
  VALUES(lesson_row.id,version_row.id,'saved',jsonb_build_object('release',release_name,
   'mode','compatible_editorial_refresh','before',snapshot,'source_hash',source_hash,'progress_unchanged',true));

  FOR block_spec IN SELECT value FROM jsonb_array_elements(spec->'blocks') LOOP
   SELECT * INTO STRICT block_row FROM public.academy_lesson_blocks
   WHERE version_id=version_row.id AND block_key=block_spec->>'key' FOR UPDATE;
   IF block_row.block_type IS DISTINCT FROM block_spec->>'type'
    OR block_row.position IS DISTINCT FROM (block_spec->>'position')::integer
    OR block_row.required IS DISTINCT FROM (block_spec->>'required')::boolean
    OR block_row.points IS DISTINCT FROM (block_spec->>'points')::integer THEN
    RAISE EXCEPTION 'Video block structure changed for %/%',lesson_row.lesson_id,block_row.block_key;
   END IF;
   IF block_spec?'evaluation' THEN
    SELECT * INTO STRICT key_row FROM academy_private.lesson_block_keys WHERE block_id=block_row.id FOR UPDATE;
    IF key_row.answer_key IS DISTINCT FROM block_spec->'evaluation'
     OR key_row.scoring IS DISTINCT FROM block_spec->'scoring' THEN
     RAISE EXCEPTION 'Video answer mapping changed for %/%',lesson_row.lesson_id,block_row.block_key;
    END IF;
    UPDATE academy_private.lesson_block_keys SET feedback=feedback||(block_spec->'feedback') WHERE block_id=block_row.id;
   END IF;
   UPDATE public.academy_lesson_blocks SET title=block_spec->>'title',content=block_spec->'content' WHERE id=block_row.id;
  END LOOP;
  validation_result:=academy_private.lesson_validation(version_row.id);
  IF jsonb_array_length(validation_result->'errors')>0 THEN
   RAISE EXCEPTION 'Invalid video lesson %: %',lesson_row.lesson_id,validation_result;
  END IF;
  UPDATE public.academy_lesson_versions SET objective=spec->>'objective',hook=spec->>'hook',
   change_note=release_name,validation=validation_result WHERE id=version_row.id;
 END LOOP;

 IF identities_before IS DISTINCT FROM {identity} THEN RAISE EXCEPTION 'Video lesson identity changed'; END IF;
 IF grading_before IS DISTINCT FROM {grading} THEN RAISE EXCEPTION 'Video grading identity changed'; END IF;
 IF learner_before IS DISTINCT FROM {learner_fingerprint()} THEN
  RAISE EXCEPTION 'Learner records changed; abort video modules 4–6 release';
 END IF;
 UPDATE public.academy_lesson_audit SET details=details||jsonb_build_object('publication_receipt',
  jsonb_build_object('release',release_name,'published_lessons',43,'blocks',645,'graded_checks',215,
   'learner_records_unchanged',true,'lesson_identity_unchanged',true,'grading_identity_unchanged',true,
   'checked_tables',learner_before,'applied_at',clock_timestamp()))
 WHERE details->>'release'=release_name AND academy_lesson_id=(SELECT id FROM public.academy_lessons WHERE module_id='s02-m04' AND lesson_id='pv04-01');
END $pv456_release$;
"""
    MIGRATION.write_text(sql)
    print(f"Packaged {len(specs)} approved lessons / 645 blocks / 215 checks: {MIGRATION.name}")


if __name__ == "__main__":
    build()
