"""Publish narrow audit repairs without replacing any learner or grading identity."""
import json
from pathlib import Path
from build_perfect_video_1215_clear_practice import TABLES, learner_fingerprint

ROOT = Path(__file__).resolve().parents[2]
PAYLOAD = ROOT / 'scripts/perfect-video/releases/audit-repairs-20261004.json'
MIGRATION = ROOT / 'supabase/migrations/20261004131422_perfect_video_audit_repairs.sql'
RELEASE = 'perfect_video_audit_repairs_20261004'


def build():
    specs = json.loads(PAYLOAD.read_text())
    def assert_public(value):
        if isinstance(value, dict):
            assert not {'evaluation', 'answer_key', 'answerKey', 'correct', 'answers', 'scoring'}.intersection(value)
            for part in value.values():
                assert_public(part)
        elif isinstance(value, list):
            for part in value:
                assert_public(part)
    assert_public(specs)
    assert len(specs) == 39 and len({s['lesson'] for s in specs}) == 39
    assert sum(s['source_blocks'] for s in specs) == 671
    assert sum(len(s['blocks']) for s in specs) == 164
    assert all(len(s['source_hash']) == 32 for s in specs)
    assert all(b['type'] not in ['course_exam', 'submission'] for s in specs for b in s['blocks'])
    payload = json.dumps(specs, ensure_ascii=False, separators=(',', ':'))
    assert '$pv_audit_payload$' not in payload
    identity = """(SELECT md5(coalesce(jsonb_agg(jsonb_build_object(
 'lesson',to_jsonb(l),'version_id',v.id,'number',v.version_number,
 'subtitle',v.subtitle,'duration',v.duration,'estimated_minutes',v.estimated_minutes,
 'source_kind',v.source_kind,'origin',v.origin_version_id) ORDER BY l.id),'[]'::jsonb)::text)
 FROM public.academy_lessons l LEFT JOIN public.academy_lesson_versions v ON v.id=l.published_version_id)"""
    grading = """(SELECT md5(coalesce(jsonb_agg(jsonb_build_object(
 'block',to_jsonb(b)-'title'-'content'-'updated_at',
 'private_key',to_jsonb(k)-'feedback'-'updated_at') ORDER BY b.id),'[]'::jsonb)::text)
 FROM public.academy_lesson_blocks b LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id)"""
    sql = f"""-- Generated by scripts/perfect-video/build_perfect_video_audit.py.
-- Audit repairs: plausible choices, four honest titles, grammar and comparative analytics.
-- Preserve all IDs, published pointers, ordering, answer mappings, scoring and learner rows.
-- No private answer keys or scoring metadata are embedded in this repository payload.
-- Archive the complete previous content in the protected editorial audit; abort on source drift.
DO $pv_audit_release$
DECLARE
 release_name text := '{RELEASE}';
 specs jsonb := $pv_audit_payload${payload}$pv_audit_payload$::jsonb;
 spec jsonb; block_spec jsonb;
 lesson_row public.academy_lessons; version_row public.academy_lesson_versions;
 block_row public.academy_lesson_blocks; key_row academy_private.lesson_block_keys;
 catalog_count integer; already integer; source_hash text; snapshot jsonb;
 learner_before jsonb; identities_before text; grading_before text; validation_before jsonb; validation_result jsonb;
BEGIN
 PERFORM set_config('lock_timeout','5s',true);
 LOCK TABLE public.academy_lessons,public.academy_lesson_versions,public.academy_lesson_blocks,
 academy_private.lesson_block_keys,public.academy_lesson_audit,
 {','.join(TABLES)} IN SHARE ROW EXCLUSIVE MODE;
 SELECT count(*) INTO catalog_count FROM public.academy_lessons l
 JOIN jsonb_array_elements(specs) s ON l.module_id=s->>'module' AND l.lesson_id=s->>'lesson';
 IF catalog_count=0 THEN RAISE NOTICE 'Video audit source absent; release skipped'; RETURN; END IF;
 IF catalog_count<>39 THEN RAISE EXCEPTION 'Expected 39 audit source lessons, found %',catalog_count; END IF;
 SELECT count(*) INTO already FROM public.academy_lessons l
 JOIN jsonb_array_elements(specs) s ON l.module_id=s->>'module' AND l.lesson_id=s->>'lesson'
 WHERE EXISTS(SELECT 1 FROM public.academy_lesson_audit a WHERE a.academy_lesson_id=l.id
 AND a.version_id=l.published_version_id AND a.details->>'release'=release_name);
 IF already=39 THEN RETURN; END IF;
 IF already<>0 THEN RAISE EXCEPTION 'Partial video audit archive; stop and inspect'; END IF;
 learner_before:={learner_fingerprint()};
 identities_before:={identity};
 grading_before:={grading};
 FOR spec IN SELECT value FROM jsonb_array_elements(specs) LOOP
  SELECT * INTO STRICT lesson_row FROM public.academy_lessons
  WHERE module_id=spec->>'module' AND lesson_id=spec->>'lesson' FOR UPDATE;
  IF lesson_row.status<>'published' OR lesson_row.published_version_id IS NULL
   OR lesson_row.published_version_id IS DISTINCT FROM lesson_row.draft_version_id THEN
   RAISE EXCEPTION 'Video publication state changed for %',lesson_row.lesson_id;
  END IF;
  SELECT * INTO STRICT version_row FROM public.academy_lesson_versions
  WHERE id=lesson_row.published_version_id FOR UPDATE;
  IF version_row.version_number IS DISTINCT FROM (spec->>'source_version')::integer THEN
   RAISE EXCEPTION 'Video version changed for %',lesson_row.lesson_id;
  END IF;
  SELECT md5(jsonb_build_object(
   'title',version_row.title,'subtitle',version_row.subtitle,'duration',version_row.duration,
   'objective',version_row.objective,'hook',version_row.hook,
   'estimated_minutes',version_row.estimated_minutes,'change_note',version_row.change_note,
   'blocks',jsonb_agg(jsonb_build_object(
    'block_key',b.block_key,'position',b.position,'block_type',b.block_type,'title',b.title,
    'content',b.content,'required',b.required,'points',b.points,
    'evaluation',coalesce(k.answer_key,'{{}}'::jsonb),'feedback',coalesce(k.feedback,'{{}}'::jsonb),
    'scoring',coalesce(k.scoring,'{{}}'::jsonb)) ORDER BY b.position))::text)
  INTO source_hash FROM public.academy_lesson_blocks b
  LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id WHERE b.version_id=version_row.id;
  IF source_hash IS DISTINCT FROM spec->>'source_hash' THEN
   RAISE EXCEPTION 'Video source drift for %',lesson_row.lesson_id;
  END IF;
  validation_before:=academy_private.lesson_validation(version_row.id);
  SELECT jsonb_build_object('version',to_jsonb(version_row),'blocks',jsonb_agg(
   to_jsonb(b)||jsonb_build_object('evaluation',coalesce(k.answer_key,'{{}}'::jsonb),
    'feedback',coalesce(k.feedback,'{{}}'::jsonb),'scoring',coalesce(k.scoring,'{{}}'::jsonb)) ORDER BY b.position))
  INTO snapshot FROM public.academy_lesson_blocks b
  LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id WHERE b.version_id=version_row.id;
  IF jsonb_array_length(snapshot->'blocks') IS DISTINCT FROM (spec->>'source_blocks')::integer THEN
   RAISE EXCEPTION 'Video block count changed for %',lesson_row.lesson_id;
  END IF;
  INSERT INTO public.academy_lesson_audit(academy_lesson_id,version_id,action,details)
  VALUES(lesson_row.id,version_row.id,'saved',jsonb_build_object('release',release_name,
   'mode','compatible_audit_repairs','before',snapshot,'source_hash',source_hash,'progress_unchanged',true));
  FOR block_spec IN SELECT value FROM jsonb_array_elements(spec->'blocks') LOOP
   SELECT * INTO STRICT block_row FROM public.academy_lesson_blocks
   WHERE version_id=version_row.id AND block_key=block_spec->>'key' FOR UPDATE;
   IF block_row.block_type IS DISTINCT FROM block_spec->>'type'
    OR block_row.position IS DISTINCT FROM (block_spec->>'position')::integer
    OR block_row.required IS DISTINCT FROM (block_spec->>'required')::boolean
    OR block_row.points IS DISTINCT FROM (block_spec->>'points')::integer THEN
    RAISE EXCEPTION 'Video block structure changed for %/%',lesson_row.lesson_id,block_row.block_key;
   END IF;
   IF block_row.block_type IN ('quiz','scenario') AND
    (SELECT jsonb_agg(o->>'id' ORDER BY n) FROM jsonb_array_elements(block_row.content->'options') WITH ORDINALITY t(o,n))
     IS DISTINCT FROM
    (SELECT jsonb_agg(o->>'id' ORDER BY n) FROM jsonb_array_elements(block_spec->'content'->'options') WITH ORDINALITY t(o,n)) THEN
    RAISE EXCEPTION 'Video option IDs changed for %/%',lesson_row.lesson_id,block_row.block_key;
   END IF;
   IF block_spec?'feedback' THEN
    SELECT * INTO STRICT key_row FROM academy_private.lesson_block_keys WHERE block_id=block_row.id FOR UPDATE;
    UPDATE academy_private.lesson_block_keys SET feedback=feedback||(block_spec->'feedback') WHERE block_id=block_row.id;
   END IF;
   UPDATE public.academy_lesson_blocks SET title=block_spec->>'title',content=block_spec->'content' WHERE id=block_row.id;
  END LOOP;
  validation_result:=academy_private.lesson_validation(version_row.id);
  IF jsonb_array_length(validation_result->'errors')>0 THEN
   RAISE EXCEPTION 'Invalid video lesson %: %',lesson_row.lesson_id,validation_result;
  END IF;
  IF validation_result->'warnings' IS DISTINCT FROM validation_before->'warnings' THEN
   RAISE EXCEPTION 'Video validation warnings changed for %',lesson_row.lesson_id;
  END IF;
  UPDATE public.academy_lesson_versions SET title=spec->>'title',objective=spec->>'objective',
   hook=spec->>'hook',change_note=release_name,validation=validation_result WHERE id=version_row.id;
 END LOOP;
 IF identities_before IS DISTINCT FROM {identity} THEN RAISE EXCEPTION 'Video lesson identity changed'; END IF;
 IF grading_before IS DISTINCT FROM {grading} THEN RAISE EXCEPTION 'Video grading identity changed'; END IF;
 IF learner_before IS DISTINCT FROM {learner_fingerprint()} THEN
  RAISE EXCEPTION 'Learner records changed; abort video audit repairs';
 END IF;
 UPDATE public.academy_lesson_audit SET details=details||jsonb_build_object('publication_receipt',
  jsonb_build_object('release',release_name,'published_lessons',39,'archived_blocks',671,'changed_blocks',164,
   'learner_records_unchanged',true,'lesson_identity_unchanged',true,'grading_identity_unchanged',true,
   'checked_tables',learner_before,'applied_at',clock_timestamp()))
 WHERE details->>'release'=release_name AND academy_lesson_id=(SELECT id FROM public.academy_lessons WHERE module_id='s02-m04' AND lesson_id='pv04-12');
END $pv_audit_release$;
"""
    MIGRATION.write_text(sql)
    print(f'Packaged {len(specs)} lessons / 164 changed blocks: {MIGRATION.name} ({len(sql)} characters)')


if __name__ == '__main__':
    build()
