"""Generate a guarded continuation; never connect to a database or read students."""
import argparse
import json
from pathlib import Path
from content_full_course import LESSONS, RELEASE


def build_sql():
    payload = json.dumps(LESSONS, ensure_ascii=False, separators=(",", ":"))
    assert "$curriculum$" not in payload
    return r'''-- Generated by scripts/silk-road/build_full_course.py; do not edit by hand.
-- 74 clearer openings; 60 optional transfer activities for M03-M11.
-- This follows the M01/M02 editorial migration. Same version and assessment IDs.
SET lock_timeout = '5s';
DO $editorial$
DECLARE
 curriculum jsonb := $curriculum$__PAYLOAD__$curriculum$::jsonb;
 release_name text := '__RELEASE__';
 spec jsonb;
 l public.academy_lessons;
 v public.academy_lesson_versions;
 old_ids uuid[];
 before_image jsonb;
 preserved jsonb;
 after_preserved jsonb;
 intro_id uuid;
 practice_id uuid;
 context_position integer;
 practice_position integer;
 eligible integer;
 already_applied integer;
 initial_progress text;
 initial_attempts text;
 result jsonb;
BEGIN
 LOCK TABLE public.academy_lessons,public.academy_lesson_versions,
   public.academy_lesson_blocks,academy_private.lesson_block_keys,
   public.academy_lesson_progress,public.academy_lesson_attempts_v2
   IN SHARE ROW EXCLUSIVE MODE;
 SELECT count(*) INTO already_applied FROM public.academy_lessons a
 JOIN jsonb_array_elements(curriculum) s ON a.module_id=s->>'module' AND a.lesson_id=s->>'lesson'
 WHERE EXISTS(SELECT 1 FROM public.academy_lesson_audit h
   WHERE h.academy_lesson_id=a.id AND h.version_id=a.published_version_id
     AND h.action='saved' AND h.details->>'release'=release_name);
 IF already_applied=74 THEN RETURN; END IF;
 IF already_applied<>0 THEN RAISE EXCEPTION 'Partial full-course editorial release'; END IF;
 SELECT count(*) INTO eligible FROM public.academy_lessons a
 JOIN public.academy_lesson_versions b ON b.id=a.published_version_id
 JOIN jsonb_array_elements(curriculum) s ON a.module_id=s->>'module' AND a.lesson_id=s->>'lesson'
 WHERE b.change_note=s->>'base' AND b.version_number=(s->>'version')::integer;
 IF eligible=0 THEN
   RAISE NOTICE 'Expected published curriculum absent; no full-course editorial changes';
   RETURN;
 END IF;
 IF eligible<>74 THEN RAISE EXCEPTION 'Expected 74 source lessons after M01/M02 release, found %',eligible; END IF;
 SELECT md5(coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.user_id,p.academy_lesson_id),'[]')::text)
   INTO initial_progress FROM public.academy_lesson_progress p;
 SELECT md5(coalesce(jsonb_agg(to_jsonb(a) ORDER BY a.id),'[]')::text)
   INTO initial_attempts FROM public.academy_lesson_attempts_v2 a;

 FOR spec IN SELECT value FROM jsonb_array_elements(curriculum) LOOP
   SELECT * INTO l FROM public.academy_lessons
     WHERE module_id=spec->>'module' AND lesson_id=spec->>'lesson' FOR UPDATE;
   SELECT * INTO v FROM public.academy_lesson_versions WHERE id=l.published_version_id FOR UPDATE;
   IF l.status<>'published' OR l.draft_version_id IS DISTINCT FROM l.published_version_id
      OR v.change_note<>spec->>'base' OR v.version_number<>(spec->>'version')::integer THEN
     RAISE EXCEPTION 'Publication drift for %/%',l.module_id,l.lesson_id;
   END IF;
   SELECT b.id INTO intro_id FROM public.academy_lesson_blocks b
     WHERE b.version_id=v.id AND b.block_key='objective' AND b.block_type='objective';
   IF intro_id IS NULL THEN RAISE EXCEPTION 'Opening missing for %',l.lesson_id; END IF;
   SELECT array_agg(b.id ORDER BY b.position),
     jsonb_build_object('version',to_jsonb(v),'blocks',jsonb_agg(to_jsonb(b)
       ||jsonb_build_object('evaluation',coalesce(k.answer_key,'{}'::jsonb),
         'feedback',coalesce(k.feedback,'{}'::jsonb),'scoring',coalesce(k.scoring,'{}'::jsonb)) ORDER BY b.position)),
     jsonb_agg(jsonb_build_object('id',b.id,'key',b.block_key,'type',b.block_type,
       'required',b.required,'points',b.points,
       'assessment',CASE WHEN b.block_type IN ('quiz','scenario','client_simulation','decision_tree',
         'matching','sequence_sort','calculator','image_hotspot','course_exam')
         THEN jsonb_build_object('content',b.content,'key',to_jsonb(k)) ELSE NULL END) ORDER BY b.block_key)
   INTO old_ids,before_image,preserved FROM public.academy_lesson_blocks b
   LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id WHERE b.version_id=v.id;
   INSERT INTO public.academy_lesson_audit(academy_lesson_id,version_id,action,details)
   VALUES(l.id,v.id,'saved',jsonb_build_object('release',release_name,
     'mode','compatible_editorial_supplement','before',before_image,
     'preserved_assessments',true,'progress_unchanged',true,'new_activities_optional',true));

   UPDATE public.academy_lesson_blocks SET title='Какво ще можеш след урока',content=spec->'intro'
     WHERE id=intro_id;
   UPDATE public.academy_lesson_versions
     SET title=coalesce(spec->>'title',title),objective=spec->'intro'->>'body',change_note=release_name
     WHERE id=v.id;
   -- Only plain unassessed body/title text; URLs and private assessment keys stay intact.
   UPDATE public.academy_lesson_blocks
     SET title=regexp_replace(title,'\mreaddy( ai)?\M(?![./])','избрания редактор','gi'),
         content=CASE WHEN jsonb_typeof(content->'body')='string' THEN jsonb_set(content,'{body}',
           to_jsonb(regexp_replace(content->>'body','\mreaddy( ai)?\M(?![./])','избрания редактор','gi')))
           ELSE content END
     WHERE version_id=v.id AND id<>intro_id AND block_type IN
       ('hook','concept','rich_text','case_study','example','summary','practical_response');

   IF spec ? 'exercise' THEN
     IF EXISTS(SELECT 1 FROM public.academy_lesson_blocks
       WHERE version_id=v.id AND block_key IN ('context_20261003','practice_20261003')) THEN
       RAISE EXCEPTION 'Unexpected existing supplement for %',l.lesson_id;
     END IF;
     UPDATE public.academy_lesson_blocks SET position=position+10000 WHERE version_id=v.id;
     UPDATE public.academy_lesson_blocks SET position=(position-10000)*10 WHERE version_id=v.id;
     SELECT position-4 INTO context_position FROM public.academy_lesson_blocks
       WHERE version_id=v.id AND block_key='practice_brief';
     SELECT position-2 INTO practice_position FROM public.academy_lesson_blocks
       WHERE version_id=v.id AND block_key='model_solution';
     IF context_position IS NULL OR practice_position IS NULL THEN
       RAISE EXCEPTION 'Practice structure missing for %',l.lesson_id;
     END IF;
     INSERT INTO public.academy_lesson_blocks(version_id,block_key,position,block_type,title,content,required,points)
     VALUES(v.id,'context_20261003',context_position,'rich_text',spec->>'context_title',spec->'context',false,0);
     INSERT INTO public.academy_lesson_blocks(version_id,block_key,position,block_type,title,content,required,points)
     VALUES(v.id,'practice_20261003',practice_position,spec->'exercise'->>'type',
       'Самопроверка по избор — нов практически случай',spec->'exercise'->'content',false,0)
     RETURNING id INTO practice_id;
     INSERT INTO academy_private.lesson_block_keys(block_id,answer_key,feedback,scoring)
     VALUES(practice_id,spec->'exercise'->'evaluation',spec->'exercise'->'feedback','{}'::jsonb);
   END IF;

   SELECT jsonb_agg(jsonb_build_object('id',b.id,'key',b.block_key,'type',b.block_type,
     'required',b.required,'points',b.points,
     'assessment',CASE WHEN b.block_type IN ('quiz','scenario','client_simulation','decision_tree',
       'matching','sequence_sort','calculator','image_hotspot','course_exam')
       THEN jsonb_build_object('content',b.content,'key',to_jsonb(k)) ELSE NULL END) ORDER BY b.block_key)
   INTO after_preserved FROM public.academy_lesson_blocks b
   LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id WHERE b.id=ANY(old_ids);
   IF preserved IS DISTINCT FROM after_preserved THEN RAISE EXCEPTION 'Assessment/progress contract changed for %',l.lesson_id; END IF;
   IF EXISTS(SELECT 1 FROM public.academy_lesson_blocks
     WHERE version_id=v.id AND NOT(id=ANY(old_ids)) AND (required OR points<>0)) THEN
     RAISE EXCEPTION 'New steps must remain optional with zero XP';
   END IF;
   result:=academy_private.lesson_validation(v.id);
   IF jsonb_array_length(result->'errors')>0 THEN RAISE EXCEPTION 'Invalid %: %',l.lesson_id,result; END IF;
   UPDATE public.academy_lesson_versions SET validation=result WHERE id=v.id;
 END LOOP;
 IF initial_progress IS DISTINCT FROM (SELECT md5(coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.user_id,p.academy_lesson_id),'[]')::text) FROM public.academy_lesson_progress p)
   OR initial_attempts IS DISTINCT FROM (SELECT md5(coalesce(jsonb_agg(to_jsonb(a) ORDER BY a.id),'[]')::text) FROM public.academy_lesson_attempts_v2 a) THEN
   RAISE EXCEPTION 'Learner records changed; abort the entire release';
 END IF;
END $editorial$;
'''.replace("__PAYLOAD__", payload).replace("__RELEASE__", RELEASE)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--migration", type=Path, required=True)
    args = parser.parse_args()
    if not args.migration.is_file() or args.migration.parent.name != "migrations":
        parser.error("Use the existing file created by supabase migration new")
    args.migration.write_text(build_sql(), encoding="utf-8")
    print("Generated 74 preserved lessons, 74 clearer openings, 60 additional optional activities")
