"""Build a guarded, progress-compatible editorial migration.

Create the empty migration with `supabase migration new` first, then pass its
actual path. This builder never connects to a database and reads no learner data.
"""
import argparse
import json
from pathlib import Path

from content_m01_m02 import BASE_RELEASE, LESSONS, RELEASE, TOOL_ROUTES


def build_sql():
    payload = json.dumps(LESSONS, ensure_ascii=False, separators=(",", ":"))
    routes = json.dumps(TOOL_ROUTES, ensure_ascii=False, separators=(",", ":"))
    assert "$curriculum$" not in payload and "$routes$" not in routes
    return r'''-- Generated by scripts/silk-road/build_m01_m02.py. Do not edit by hand.
-- Progress-compatible continuation of the September 24 published curriculum.
-- Keep lesson/version/block IDs, required flags, points and existing assessments.
-- Archive the complete original content in the existing admin-only audit table.
-- All new activities are optional, have zero XP and award no new assessment credit.
SET lock_timeout = '5s';

DO $editorial$
DECLARE
  curriculum jsonb := $curriculum$__PAYLOAD__$curriculum$::jsonb;
  routes jsonb := $routes$__ROUTES__$routes$::jsonb;
  release_name text := '__RELEASE__';
  base_release text := '__BASE__';
  spec jsonb;
  lesson public.academy_lessons;
  version public.academy_lesson_versions;
  snapshot jsonb;
  preserved jsonb;
  after_preserved jsonb;
  old_ids uuid[];
  new_id uuid;
  context_position integer;
  activity_position integer;
  initial_progress text;
  final_progress text;
  initial_attempts text;
  final_attempts text;
  validation_result jsonb;
  eligible integer;
  already_applied integer;
  target_count integer := jsonb_array_length(curriculum);
BEGIN
  -- Content and completion requests cannot interleave with this small release.
  LOCK TABLE public.academy_lessons, public.academy_lesson_versions,
    public.academy_lesson_blocks, academy_private.lesson_block_keys,
    public.academy_lesson_progress, public.academy_lesson_attempts_v2
    IN SHARE ROW EXCLUSIVE MODE;

  SELECT count(*) INTO already_applied FROM public.academy_lessons l
  JOIN jsonb_array_elements(curriculum) s ON l.module_id=s->>'module' AND l.lesson_id=s->>'lesson'
  WHERE EXISTS(SELECT 1 FROM public.academy_lesson_audit a
    WHERE a.academy_lesson_id=l.id AND a.version_id=l.published_version_id
      AND a.action='saved' AND a.details->>'release'=release_name);
  IF already_applied=target_count THEN RETURN; END IF;
  IF already_applied<>0 THEN RAISE EXCEPTION 'Partial editorial release; stop and inspect'; END IF;

  SELECT count(*) INTO eligible FROM public.academy_lessons l
  JOIN public.academy_lesson_versions v ON v.id=l.published_version_id
  JOIN jsonb_array_elements(curriculum) s ON l.module_id=s->>'module' AND l.lesson_id=s->>'lesson'
  WHERE v.change_note=base_release;
  IF eligible=0 THEN
    -- Older clean-install fixtures do not include the September 24 publication.
    -- They must not be silently upgraded with a different or incomplete source.
    RAISE NOTICE 'September 24 M01/M02 publication absent; no editorial changes';
    RETURN;
  END IF;
  IF eligible<>target_count THEN RAISE EXCEPTION 'Expected all 14 base lessons, found %',eligible; END IF;

  SELECT md5(coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.user_id,p.academy_lesson_id),'[]')::text)
    INTO initial_progress FROM public.academy_lesson_progress p;
  SELECT md5(coalesce(jsonb_agg(to_jsonb(a) ORDER BY a.id),'[]')::text)
    INTO initial_attempts FROM public.academy_lesson_attempts_v2 a;

  FOR spec IN SELECT value FROM jsonb_array_elements(curriculum) LOOP
    SELECT * INTO lesson FROM public.academy_lessons
      WHERE module_id=spec->>'module' AND lesson_id=spec->>'lesson' FOR UPDATE;
    SELECT * INTO version FROM public.academy_lesson_versions
      WHERE id=lesson.published_version_id FOR UPDATE;
    IF lesson.status<>'published' OR lesson.draft_version_id IS DISTINCT FROM lesson.published_version_id
       OR version.change_note<>base_release
       OR version.version_number<>(CASE WHEN lesson.module_id='s01-m01' THEN 9 ELSE 7 END) THEN
      RAISE EXCEPTION 'Publication/draft drift for %/%',lesson.module_id,lesson.lesson_id;
    END IF;

    SELECT array_agg(b.id ORDER BY b.position),
      jsonb_build_object('version',to_jsonb(version),'blocks',jsonb_agg(to_jsonb(b)
        ||jsonb_build_object('evaluation',coalesce(k.answer_key,'{}'::jsonb),
          'feedback',coalesce(k.feedback,'{}'::jsonb),'scoring',coalesce(k.scoring,'{}'::jsonb)) ORDER BY b.position)),
      jsonb_agg(jsonb_build_object('id',b.id,'key',b.block_key,'type',b.block_type,
        'required',b.required,'points',b.points,
        'assessment',CASE WHEN b.block_type IN ('quiz','scenario','client_simulation','decision_tree',
          'matching','sequence_sort','calculator','image_hotspot','course_exam')
          THEN jsonb_build_object('content',b.content,'key',to_jsonb(k)) ELSE NULL END) ORDER BY b.block_key)
    INTO old_ids,snapshot,preserved
    FROM public.academy_lesson_blocks b
    LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id
    WHERE b.version_id=version.id;

    IF coalesce(cardinality(old_ids),0)<10
       OR NOT EXISTS(SELECT 1 FROM public.academy_lesson_blocks WHERE version_id=version.id AND block_key='practice_brief')
       OR NOT EXISTS(SELECT 1 FROM public.academy_lesson_blocks WHERE version_id=version.id AND block_key='model_solution') THEN
      RAISE EXCEPTION 'Unexpected base structure for %/%',lesson.module_id,lesson.lesson_id;
    END IF;

    -- The before-image is admin-only and retains original block IDs, positions,
    -- source URLs, answer keys and metadata for an exact editorial rollback.
    INSERT INTO public.academy_lesson_audit(academy_lesson_id,version_id,action,details)
    VALUES(lesson.id,version.id,'saved',jsonb_build_object(
      'release',release_name,'mode','compatible_editorial_supplement',
      'before',snapshot,'preserved_assessments',true,'progress_unchanged',true,
      'new_activities_optional',true));

    UPDATE public.academy_lesson_versions
      SET title=spec->>'title',change_note=release_name WHERE id=version.id;
    -- Only neutralize editor-specific wording in unassessed content.
    UPDATE public.academy_lesson_blocks
      SET title=replace(replace(title,'Readdy AI','избрания редактор'),'Readdy','избрания редактор'),
          content=replace(replace(content::text,'Readdy AI','избрания редактор'),'Readdy','избрания редактор')::jsonb
      WHERE version_id=version.id AND block_type IN
        ('objective','hook','concept','rich_text','case_study','example','summary','practical_response');

    -- Move through an empty range first; UNIQUE(version_id,position) is immediate.
    UPDATE public.academy_lesson_blocks SET position=position+10000 WHERE version_id=version.id;
    UPDATE public.academy_lesson_blocks SET position=(position-10000)*10 WHERE version_id=version.id;
    SELECT position-4 INTO context_position FROM public.academy_lesson_blocks
      WHERE version_id=version.id AND block_key='practice_brief';
    IF lesson.lesson_id IN ('l01-01','l02-01') THEN context_position:=5; END IF;
    SELECT position-2 INTO activity_position FROM public.academy_lesson_blocks
      WHERE version_id=version.id AND block_key='model_solution';

    INSERT INTO public.academy_lesson_blocks(version_id,block_key,position,block_type,title,content,required,points)
    VALUES(version.id,'context_20261003',context_position,'rich_text',spec->>'context_title',spec->'context',false,0);
    IF coalesce((spec->>'routes')::boolean,false) THEN
      INSERT INTO public.academy_lesson_blocks(version_id,block_key,position,block_type,title,content,required,points)
      VALUES(version.id,'routes_20261003',context_position+1,'rich_text','Учебен старт без покупка',routes,false,0);
    END IF;
    INSERT INTO public.academy_lesson_blocks(version_id,block_key,position,block_type,title,content,required,points)
    VALUES(version.id,'practice_20261003',activity_position,spec->'exercise'->>'type',
      'Самопроверка по избор — нов практически случай',spec->'exercise'->'content',false,0)
    RETURNING id INTO new_id;
    INSERT INTO academy_private.lesson_block_keys(block_id,answer_key,feedback,scoring)
    VALUES(new_id,spec->'exercise'->'evaluation',spec->'exercise'->'feedback','{}'::jsonb);

    SELECT jsonb_agg(jsonb_build_object('id',b.id,'key',b.block_key,'type',b.block_type,
      'required',b.required,'points',b.points,
      'assessment',CASE WHEN b.block_type IN ('quiz','scenario','client_simulation','decision_tree',
        'matching','sequence_sort','calculator','image_hotspot','course_exam')
        THEN jsonb_build_object('content',b.content,'key',to_jsonb(k)) ELSE NULL END) ORDER BY b.block_key)
    INTO after_preserved FROM public.academy_lesson_blocks b
    LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id
    WHERE b.id=ANY(old_ids);
    IF preserved IS DISTINCT FROM after_preserved THEN
      RAISE EXCEPTION 'Existing completion or assessment changed for %/%',lesson.module_id,lesson.lesson_id;
    END IF;
    IF EXISTS(SELECT 1 FROM public.academy_lesson_blocks
      WHERE version_id=version.id AND NOT(id=ANY(old_ids)) AND (required OR points<>0)) THEN
      RAISE EXCEPTION 'New blocks must not invalidate progress or grant XP';
    END IF;
    validation_result:=academy_private.lesson_validation(version.id);
    IF jsonb_array_length(validation_result->'errors')>0 THEN
      RAISE EXCEPTION 'Editorial validation failed for %/%: %',lesson.module_id,lesson.lesson_id,validation_result;
    END IF;
    UPDATE public.academy_lesson_versions SET validation=validation_result WHERE id=version.id;
  END LOOP;

  SELECT md5(coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.user_id,p.academy_lesson_id),'[]')::text)
    INTO final_progress FROM public.academy_lesson_progress p;
  SELECT md5(coalesce(jsonb_agg(to_jsonb(a) ORDER BY a.id),'[]')::text)
    INTO final_attempts FROM public.academy_lesson_attempts_v2 a;
  IF initial_progress IS DISTINCT FROM final_progress OR initial_attempts IS DISTINCT FROM final_attempts THEN
    RAISE EXCEPTION 'Learner records changed; the whole release is rolled back';
  END IF;
END $editorial$;
'''.replace("__PAYLOAD__", payload).replace("__ROUTES__", routes).replace("__RELEASE__", RELEASE).replace("__BASE__", BASE_RELEASE)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--migration", required=True, type=Path)
    args = parser.parse_args()
    if not args.migration.is_file() or args.migration.parent.name != "migrations":
        parser.error("Pass an existing empty file created by supabase migration new")
    if len(LESSONS) != 14 or len({(x["module"], x["lesson"]) for x in LESSONS}) != 14:
        raise ValueError("The release must contain the 14 existing M01/M02 lessons")
    args.migration.write_text(build_sql(), encoding="utf-8")
    print(f"Generated {args.migration.name}: 14 preserved lessons, 14 optional self-checks")
