"""Fill a CLI-created migration; archive originals and retain all existing learner records."""
import argparse
import json
from pathlib import Path
from content_start import BASE_RELEASE, BLOCKS, CORRECTIONS, DISTRACTORS, FEEDBACK_FIX, RELEASE


def encoded(value):
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def build_sql():
    targets = sorted({b["lesson"] for b in BLOCKS} | {b["lesson"] for b in CORRECTIONS + DISTRACTORS} | {FEEDBACK_FIX["lesson"]})
    tables = ['public.academy_lesson_progress', 'public.academy_lesson_attempts_v2', 'academy_private.lesson_progress_history', 'public.pdf_progress', 'public.profiles', 'public.academy_access_grants', 'public.academy_user_badges']
    fingerprint = "jsonb_build_object(" + ",".join(f"'{table}',(SELECT jsonb_build_object('rows',count(*),'hash',md5(coalesce(jsonb_agg(to_jsonb(t) ORDER BY to_jsonb(t)::text),'[]'::jsonb)::text)) FROM {table} t)" for table in tables) + ")"
    sql = r'''-- Generated by scripts/silk-road/build_start.py into a CLI-created file.
-- Editorial fixes, one beginner packet and optional independent checks.
-- Existing lesson/version/block identities, correct answers, points and learner rows are retained.
-- Historical attempt feedback is not rewritten; only future feedback receives the factual correction.
SET lock_timeout = '5s';
DO $start$
DECLARE
 targets jsonb := $targets$__TARGETS__$targets$::jsonb;
 additions jsonb := $additions$__BLOCKS__$additions$::jsonb;
 corrections jsonb := $corrections$__CORRECTIONS__$corrections$::jsonb;
 distractors jsonb := $distractors$__DISTRACTORS__$distractors$::jsonb;
 feedback_fix jsonb := $feedback_fix$__FEEDBACK__$feedback_fix$::jsonb;
 release_name text := '__RELEASE__';
 base_release text := '__BASE__';
 lesson_key text; lesson_row public.academy_lessons; version_row public.academy_lesson_versions;
 spec jsonb; block_row public.academy_lesson_blocks; key_row academy_private.lesson_block_keys;
 snapshot jsonb; old_ids uuid[]; new_id uuid; insert_position integer;
 learner_before jsonb; identity_before text; grade_before jsonb; grade_after jsonb;
 option_index integer; validation_result jsonb;
 already integer; eligible integer;
BEGIN
 LOCK TABLE public.academy_lessons,public.academy_lesson_versions,public.academy_lesson_blocks,
 academy_private.lesson_block_keys,__LEARNER_TABLES__ IN SHARE ROW EXCLUSIVE MODE;
 SELECT count(*) INTO already FROM public.academy_lessons l
 JOIN jsonb_array_elements_text(targets) t(lesson_key) ON l.lesson_id=t.lesson_key AND l.module_id='s01-m'||substring(t.lesson_key,2,2)
 WHERE EXISTS(SELECT 1 FROM public.academy_lesson_audit a WHERE a.academy_lesson_id=l.id AND a.version_id=l.published_version_id AND a.details->>'release'=release_name);
 IF already=jsonb_array_length(targets) THEN RETURN; END IF;
 IF already<>0 THEN RAISE EXCEPTION 'Partial beginner release; stop and inspect'; END IF;
 SELECT count(*) INTO eligible FROM public.academy_lessons l
 JOIN public.academy_lesson_versions v ON v.id=l.published_version_id
 JOIN jsonb_array_elements_text(targets) t(lesson_key) ON l.lesson_id=t.lesson_key AND l.module_id='s01-m'||substring(t.lesson_key,2,2)
 WHERE v.change_note=base_release AND l.status='published' AND l.draft_version_id=l.published_version_id;
 IF eligible=0 THEN RAISE NOTICE 'Full October base absent; beginner migration skipped'; RETURN; END IF;
 IF eligible<>jsonb_array_length(targets) THEN RAISE EXCEPTION 'Expected % published base lessons, found %',jsonb_array_length(targets),eligible; END IF;
 learner_before:=__FINGERPRINT__;
 SELECT md5(jsonb_agg(jsonb_build_object('id',l.id,'module',l.module_id,'lesson',l.lesson_id,'status',l.status,'published',l.published_version_id,'draft',l.draft_version_id,'number',v.version_number) ORDER BY l.id)::text)
 INTO identity_before FROM public.academy_lessons l LEFT JOIN public.academy_lesson_versions v ON v.id=l.published_version_id;

 FOR lesson_key IN SELECT value FROM jsonb_array_elements_text(targets) LOOP
  SELECT * INTO STRICT lesson_row FROM public.academy_lessons WHERE lesson_id=lesson_key AND module_id='s01-m'||substring(lesson_key,2,2) FOR UPDATE;
  SELECT * INTO STRICT version_row FROM public.academy_lesson_versions WHERE id=lesson_row.published_version_id FOR UPDATE;
  SELECT array_agg(b.id ORDER BY b.position),jsonb_build_object('version',to_jsonb(version_row),'blocks',jsonb_agg(to_jsonb(b)||jsonb_build_object('evaluation',coalesce(k.answer_key,'{}'),'feedback',coalesce(k.feedback,'{}'),'scoring',coalesce(k.scoring,'{}')) ORDER BY b.position)),
   jsonb_agg(jsonb_build_object('id',b.id,'key',b.block_key,'type',b.block_type,'required',b.required,'points',b.points,'answer',k.answer_key,'scoring',k.scoring,'question',b.content->>'question','options',CASE WHEN b.block_type='quiz' THEN (SELECT jsonb_agg(o->'id' ORDER BY ord) FROM jsonb_array_elements(b.content->'options') WITH ORDINALITY e(o,ord)) ELSE NULL END,'correct_label',CASE WHEN b.block_type='quiz' THEN (SELECT o->>'label' FROM jsonb_array_elements(b.content->'options') o WHERE o->>'id'=k.answer_key->>'correct') ELSE NULL END,'graded_content',CASE WHEN b.block_type IN ('scenario','matching','client_simulation','sequence_sort','calculator','decision_tree','image_hotspot','course_exam') THEN b.content ELSE NULL END,'feedback',CASE WHEN lesson_row.lesson_id='l02-06' AND b.block_key='quiz_2' THEN k.feedback-'explanation' ELSE k.feedback END) ORDER BY b.id)
  INTO old_ids,snapshot,grade_before FROM public.academy_lesson_blocks b LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id WHERE b.version_id=version_row.id;
  INSERT INTO public.academy_lesson_audit(academy_lesson_id,version_id,action,details)
  VALUES(lesson_row.id,version_row.id,'saved',jsonb_build_object('release',release_name,'mode','compatible_beginner_supplement','before',snapshot,'progress_unchanged',true,'correct_answers_unchanged',true,'new_checks_optional',true));

  FOR spec IN SELECT value FROM jsonb_array_elements(corrections) WHERE value->>'lesson'=lesson_key LOOP
   SELECT * INTO STRICT block_row FROM public.academy_lesson_blocks WHERE version_id=version_row.id AND block_key=spec->>'key';
   IF block_row.block_type<>'rich_text' OR position(spec->>'old' in coalesce(block_row.content->>'body',''))=0 THEN RAISE EXCEPTION 'Editorial source drift for %/%',lesson_key,spec->>'key'; END IF;
   UPDATE public.academy_lesson_blocks SET content=jsonb_set(content,'{body}',to_jsonb(replace(content->>'body',spec->>'old',spec->>'new'))) WHERE id=block_row.id;
  END LOOP;
  IF lesson_key=feedback_fix->>'lesson' THEN
   SELECT * INTO STRICT block_row FROM public.academy_lesson_blocks WHERE version_id=version_row.id AND block_key=feedback_fix->>'key';
   SELECT * INTO STRICT key_row FROM academy_private.lesson_block_keys WHERE block_id=block_row.id;
   IF key_row.feedback->>'explanation'<>feedback_fix->>'old' THEN RAISE EXCEPTION 'Feedback source drift'; END IF;
   UPDATE academy_private.lesson_block_keys SET feedback=jsonb_set(feedback,'{explanation}',to_jsonb(feedback_fix->>'new')) WHERE block_id=block_row.id;
  END IF;
  FOR spec IN SELECT value FROM jsonb_array_elements(distractors) WHERE value->>'lesson'=lesson_key LOOP
   SELECT * INTO STRICT block_row FROM public.academy_lesson_blocks WHERE version_id=version_row.id AND block_key=spec->>'key';
   SELECT * INTO STRICT key_row FROM academy_private.lesson_block_keys WHERE block_id=block_row.id;
   SELECT (ord-1)::integer INTO STRICT option_index FROM jsonb_array_elements(block_row.content->'options') WITH ORDINALITY e(o,ord) WHERE o->>'id'=spec->>'id' AND o->>'label'=spec->>'old';
   IF block_row.block_type<>'quiz' OR key_row.answer_key->>'correct'=spec->>'id' THEN RAISE EXCEPTION 'Only known incorrect distractors may change'; END IF;
   UPDATE public.academy_lesson_blocks SET content=jsonb_set(content,ARRAY['options',option_index::text,'label'],to_jsonb(spec->>'new')) WHERE id=block_row.id;
  END LOOP;

  IF EXISTS(SELECT 1 FROM jsonb_array_elements(additions) s WHERE s->>'lesson'=lesson_key) THEN
   -- Move through an empty range to retain the immediate unique position constraint.
   UPDATE public.academy_lesson_blocks SET position=position+100000 WHERE version_id=version_row.id;
   UPDATE public.academy_lesson_blocks SET position=(position-100000)*20 WHERE version_id=version_row.id;
   SELECT position INTO STRICT insert_position FROM public.academy_lesson_blocks WHERE version_id=version_row.id AND block_key='summary';
   FOR spec IN SELECT value FROM jsonb_array_elements(additions) WHERE value->>'lesson'=lesson_key LOOP
    INSERT INTO public.academy_lesson_blocks(version_id,block_key,position,block_type,title,content,required,points)
    VALUES(version_row.id,spec->>'key',insert_position-15,spec->>'type',spec->>'title',spec->'content',false,0) RETURNING id INTO new_id;
    insert_position:=insert_position+1;
    IF spec?'evaluation' THEN INSERT INTO academy_private.lesson_block_keys(block_id,answer_key,feedback,scoring) VALUES(new_id,spec->'evaluation',spec->'feedback','{}'); END IF;
   END LOOP;
  END IF;
  SELECT jsonb_agg(jsonb_build_object('id',b.id,'key',b.block_key,'type',b.block_type,'required',b.required,'points',b.points,'answer',k.answer_key,'scoring',k.scoring,'question',b.content->>'question','options',CASE WHEN b.block_type='quiz' THEN (SELECT jsonb_agg(o->'id' ORDER BY ord) FROM jsonb_array_elements(b.content->'options') WITH ORDINALITY e(o,ord)) ELSE NULL END,'correct_label',CASE WHEN b.block_type='quiz' THEN (SELECT o->>'label' FROM jsonb_array_elements(b.content->'options') o WHERE o->>'id'=k.answer_key->>'correct') ELSE NULL END,'graded_content',CASE WHEN b.block_type IN ('scenario','matching','client_simulation','sequence_sort','calculator','decision_tree','image_hotspot','course_exam') THEN b.content ELSE NULL END,'feedback',CASE WHEN lesson_row.lesson_id='l02-06' AND b.block_key='quiz_2' THEN k.feedback-'explanation' ELSE k.feedback END) ORDER BY b.id)
  INTO grade_after FROM public.academy_lesson_blocks b LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id WHERE b.id=ANY(old_ids);
  IF grade_before IS DISTINCT FROM grade_after THEN RAISE EXCEPTION 'Existing grading identity changed for %',lesson_key; END IF;
  IF EXISTS(SELECT 1 FROM public.academy_lesson_blocks WHERE version_id=version_row.id AND NOT(id=ANY(old_ids)) AND (required OR points<>0)) THEN RAISE EXCEPTION 'New activity changed completion or XP'; END IF;
  validation_result:=academy_private.lesson_validation(version_row.id);
  IF jsonb_array_length(validation_result->'errors')>0 THEN RAISE EXCEPTION 'Invalid beginner publication: %',lesson_key; END IF;
  UPDATE public.academy_lesson_versions SET change_note=release_name,validation=validation_result WHERE id=version_row.id;
 END LOOP;
 IF learner_before IS DISTINCT FROM __FINGERPRINT__ THEN RAISE EXCEPTION 'Learner records changed; abort beginner release'; END IF;
 IF identity_before IS DISTINCT FROM (SELECT md5(jsonb_agg(jsonb_build_object('id',l.id,'module',l.module_id,'lesson',l.lesson_id,'status',l.status,'published',l.published_version_id,'draft',l.draft_version_id,'number',v.version_number) ORDER BY l.id)::text) FROM public.academy_lessons l LEFT JOIN public.academy_lesson_versions v ON v.id=l.published_version_id) THEN RAISE EXCEPTION 'Published identity changed'; END IF;
 IF (SELECT count(*) FROM public.academy_lesson_blocks b JOIN public.academy_lessons l ON l.published_version_id=b.version_id WHERE l.module_id LIKE 's01-%' AND b.block_key LIKE 'checkpoint_%_20261003')<>6 THEN RAISE EXCEPTION 'Missing independent checkpoints'; END IF;
 UPDATE public.academy_lesson_audit SET details=details||jsonb_build_object('publication_receipt',jsonb_build_object('release',release_name,'published_lessons',jsonb_array_length(targets),'optional_blocks',jsonb_array_length(additions),'independent_checks',6,'applied_at',clock_timestamp(),'learner_records_unchanged',true,'lesson_identity_unchanged',true,'correct_answers_unchanged',true,'checked_tables',learner_before))
 WHERE version_id=(SELECT published_version_id FROM public.academy_lessons WHERE module_id='s01-m01' AND lesson_id='l01-01') AND details->>'release'=release_name;
END $start$;
'''
    replacements = {'__TARGETS__':encoded(targets),'__BLOCKS__':encoded(BLOCKS),'__CORRECTIONS__':encoded(CORRECTIONS),'__DISTRACTORS__':encoded(DISTRACTORS),'__FEEDBACK__':encoded(FEEDBACK_FIX),'__BASE__':BASE_RELEASE,'__RELEASE__':RELEASE,'__LEARNER_TABLES__':','.join(tables),'__FINGERPRINT__':fingerprint}
    for key, value in replacements.items():
        sql=sql.replace(key,value)
    assert '__' not in sql
    return sql


if __name__ == '__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--migration',required=True,type=Path)
    args=parser.parse_args()
    if not args.migration.exists():
        raise SystemExit('Create the migration with the Supabase CLI first.')
    args.migration.write_text(build_sql(),encoding='utf-8')
    print('Generated a guarded beginner release for 10 existing lessons, with 13 optional blocks and 6 independent checks.')
