"""Publish researched Marketing Basics modules 6–10 and six earlier lessons with retained progress and grading.

The input contains public content only. Real private keys stay in the database.
"""
import json
from pathlib import Path
TABLES = [
    "public.academy_lesson_progress", "public.academy_lesson_attempts_v2",
    "academy_private.lesson_progress_history", "public.pdf_progress", "public.profiles",
    "public.academy_access_grants", "public.academy_user_badges",
]


def learner_fingerprint():
    return "jsonb_build_object(" + ",\n  ".join(
        f"'{table}',(SELECT jsonb_build_object('rows',count(*),'hash',"
        "md5(coalesce(jsonb_agg(to_jsonb(x) ORDER BY to_jsonb(x)::text),'[]'::jsonb)::text)) "
        f"FROM {table} x)" for table in TABLES) + ")"


ROOT = Path(__file__).resolve().parents[2]
PAYLOAD = ROOT / 'scripts/marketing-basics/releases/modules-6-10-20261007.json'
MIGRATION = ROOT / 'supabase/migrations/20261007065643_marketing_basics_modules_6_10_strategy_practice.sql'
RELEASE = 'marketing_basics_modules_6_10_strategy_practice_20261007'


def build():
    specs = json.loads(PAYLOAD.read_text())
    def assert_public(value):
        if isinstance(value, dict):
            assert not {'evaluation', 'answer_key', 'answerKey', 'correct', 'answers', 'scoring'}.intersection(value)
            for part in value.values():
                assert_public(part)
        elif isinstance(value, list):
            for part in value:
                assert_public(part)
    assert_public(specs)
    assert len(specs) == 68 and len({s['lesson'] for s in specs}) == 68
    assert sum(s['source_blocks'] for s in specs) == 921
    assert sum(len(s['blocks']) for s in specs) == 667
    assert {m: sum(s['module']==m for s in specs) for m in sorted({s['module'] for s in specs})} == {'s03-m01':1,'s03-m02':2,'s03-m03':2,'s03-m05':1,'s03-m06':12,'s03-m07':10,'s03-m08':14,'s03-m09':14,'s03-m10':12}
    assert all(len(s['source_hash']) == 32 for s in specs)
    assert all(b['type'] not in ['course_exam', 'submission'] for s in specs for b in s['blocks'])
    payload = json.dumps(specs, ensure_ascii=False, separators=(',', ':'))
    assert '$mb610_payload$' not in payload
    identity = """(SELECT md5(coalesce(jsonb_agg(jsonb_build_object(
 'lesson',to_jsonb(l),'version_id',v.id,'number',v.version_number,
 'subtitle',v.subtitle,'duration',v.duration,'estimated_minutes',v.estimated_minutes,
 'source_kind',v.source_kind,'origin',v.origin_version_id) ORDER BY l.id),'[]'::jsonb)::text)
 FROM public.academy_lessons l LEFT JOIN public.academy_lesson_versions v ON v.id=l.published_version_id)"""
    grading = """(SELECT md5(coalesce(jsonb_agg(jsonb_build_object(
 'block',to_jsonb(b)-'title'-'content'-'updated_at',
 'private_key',to_jsonb(k)-'feedback'-'updated_at') ORDER BY b.id),'[]'::jsonb)::text)
 FROM public.academy_lesson_blocks b LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id)"""
    outside = """(SELECT md5(coalesce(jsonb_agg(jsonb_build_object(
 'version',to_jsonb(v),'block',to_jsonb(b),'key',to_jsonb(k)) ORDER BY b.id),'[]'::jsonb)::text)
 FROM public.academy_lessons l JOIN public.academy_lesson_versions v ON v.id=l.published_version_id
 JOIN public.academy_lesson_blocks b ON b.version_id=v.id
 LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id
 WHERE NOT EXISTS(SELECT 1 FROM jsonb_array_elements(specs) s
 WHERE l.module_id=s->>'module' AND l.lesson_id=s->>'lesson'))"""
    sql = f"""-- Generated by scripts/marketing-basics/build_6_10.py.
-- Clear outcomes, independent tasks, worked examples and actionable self-checks for 68 lessons.
-- Preserve all IDs, published pointers, ordering, answer mappings, scoring and learner rows.
-- No private answer keys or scoring metadata are embedded in this repository payload.
-- Archive the complete previous content in the protected editorial audit; abort on source drift.
DO $mb610_release$
DECLARE
 release_name text := '{RELEASE}';
 specs jsonb := $mb610_payload${payload}$mb610_payload$::jsonb;
 spec jsonb; block_spec jsonb;
 lesson_row public.academy_lessons; version_row public.academy_lesson_versions;
 block_row public.academy_lesson_blocks; key_row academy_private.lesson_block_keys;
 catalog_count integer; already integer; source_hash text; snapshot jsonb;
 learner_before jsonb; identities_before text; grading_before text; outside_before text; validation_before jsonb; validation_result jsonb;
BEGIN
 PERFORM set_config('lock_timeout','5s',true);
 LOCK TABLE public.academy_lessons,public.academy_lesson_versions,public.academy_lesson_blocks,
 academy_private.lesson_block_keys,public.academy_lesson_audit,
 {','.join(TABLES)} IN SHARE ROW EXCLUSIVE MODE;
 SELECT count(*) INTO catalog_count FROM public.academy_lessons l
 JOIN jsonb_array_elements(specs) s ON l.module_id=s->>'module' AND l.lesson_id=s->>'lesson';
 IF catalog_count=0 THEN RAISE NOTICE 'Marketing audit source absent; release skipped'; RETURN; END IF;
 IF catalog_count<>68 THEN RAISE EXCEPTION 'Expected 68 audit source lessons, found %',catalog_count; END IF;
 SELECT count(*) INTO already FROM public.academy_lessons l
 JOIN jsonb_array_elements(specs) s ON l.module_id=s->>'module' AND l.lesson_id=s->>'lesson'
 WHERE EXISTS(SELECT 1 FROM public.academy_lesson_audit a WHERE a.academy_lesson_id=l.id
 AND a.version_id=l.published_version_id AND a.details->>'release'=release_name);
 IF already=68 THEN RETURN; END IF;
 IF already<>0 THEN RAISE EXCEPTION 'Partial marketing audit archive; stop and inspect'; END IF;
 learner_before:={learner_fingerprint()};
 identities_before:={identity};
 grading_before:={grading};
 outside_before:={outside};
 FOR spec IN SELECT value FROM jsonb_array_elements(specs) LOOP
  SELECT * INTO STRICT lesson_row FROM public.academy_lessons
  WHERE module_id=spec->>'module' AND lesson_id=spec->>'lesson' FOR UPDATE;
  IF lesson_row.status<>'published' OR lesson_row.published_version_id IS NULL
   OR lesson_row.published_version_id IS DISTINCT FROM lesson_row.draft_version_id THEN
   RAISE EXCEPTION 'Marketing publication state changed for %',lesson_row.lesson_id;
  END IF;
  SELECT * INTO STRICT version_row FROM public.academy_lesson_versions
  WHERE id=lesson_row.published_version_id FOR UPDATE;
  IF version_row.version_number IS DISTINCT FROM (spec->>'source_version')::integer THEN
   RAISE EXCEPTION 'Marketing version changed for %',lesson_row.lesson_id;
  END IF;
  SELECT md5(jsonb_build_object(
   'title',version_row.title,'subtitle',version_row.subtitle,'duration',version_row.duration,
   'objective',version_row.objective,'hook',version_row.hook,
   'estimated_minutes',version_row.estimated_minutes,'change_note',version_row.change_note,
   'blocks',jsonb_agg(jsonb_build_object(
    'block_key',b.block_key,'position',b.position,'block_type',b.block_type,'title',b.title,
    'content',b.content,'required',b.required,'points',b.points,
    'evaluation',coalesce(k.answer_key,'{{}}'::jsonb),'feedback',coalesce(k.feedback,'{{}}'::jsonb),
    'scoring',coalesce(k.scoring,'{{}}'::jsonb)) ORDER BY b.position))::text)
  INTO source_hash FROM public.academy_lesson_blocks b
  LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id WHERE b.version_id=version_row.id;
  IF source_hash IS DISTINCT FROM spec->>'source_hash' THEN
   RAISE EXCEPTION 'Marketing source drift for %',lesson_row.lesson_id;
  END IF;
  validation_before:=academy_private.lesson_validation(version_row.id);
  SELECT jsonb_build_object('version',to_jsonb(version_row),'blocks',jsonb_agg(
   to_jsonb(b)||jsonb_build_object('evaluation',coalesce(k.answer_key,'{{}}'::jsonb),
    'feedback',coalesce(k.feedback,'{{}}'::jsonb),'scoring',coalesce(k.scoring,'{{}}'::jsonb)) ORDER BY b.position))
  INTO snapshot FROM public.academy_lesson_blocks b
  LEFT JOIN academy_private.lesson_block_keys k ON k.block_id=b.id WHERE b.version_id=version_row.id;
  IF jsonb_array_length(snapshot->'blocks') IS DISTINCT FROM (spec->>'source_blocks')::integer THEN
   RAISE EXCEPTION 'Marketing block count changed for %',lesson_row.lesson_id;
  END IF;
  INSERT INTO public.academy_lesson_audit(academy_lesson_id,version_id,action,details)
  VALUES(lesson_row.id,version_row.id,'saved',jsonb_build_object('release',release_name,
   'mode','compatible_strategy_practice','before',snapshot,'source_hash',source_hash,'progress_unchanged',true));
  FOR block_spec IN SELECT value FROM jsonb_array_elements(spec->'blocks') LOOP
   SELECT * INTO STRICT block_row FROM public.academy_lesson_blocks
   WHERE version_id=version_row.id AND block_key=block_spec->>'key' FOR UPDATE;
   IF block_row.block_type IS DISTINCT FROM block_spec->>'type'
    OR block_row.position IS DISTINCT FROM (block_spec->>'position')::integer
    OR block_row.required IS DISTINCT FROM (block_spec->>'required')::boolean
    OR block_row.points IS DISTINCT FROM (block_spec->>'points')::integer THEN
    RAISE EXCEPTION 'Marketing block structure changed for %/%',lesson_row.lesson_id,block_row.block_key;
   END IF;
   IF block_row.block_type IN ('quiz','scenario') AND
    (SELECT jsonb_agg(o->>'id' ORDER BY o->>'id') FROM jsonb_array_elements(block_row.content->'options') t(o))
     IS DISTINCT FROM
    (SELECT jsonb_agg(o->>'id' ORDER BY o->>'id') FROM jsonb_array_elements(block_spec->'content'->'options') t(o)) THEN
    RAISE EXCEPTION 'Marketing option IDs changed for %/%',lesson_row.lesson_id,block_row.block_key;
   END IF;
   IF block_spec?'feedback' THEN
    SELECT * INTO STRICT key_row FROM academy_private.lesson_block_keys WHERE block_id=block_row.id FOR UPDATE;
    UPDATE academy_private.lesson_block_keys SET feedback=feedback||(block_spec->'feedback') WHERE block_id=block_row.id;
   END IF;
   UPDATE public.academy_lesson_blocks SET title=block_spec->>'title',content=block_spec->'content' WHERE id=block_row.id;
  END LOOP;
  validation_result:=academy_private.lesson_validation(version_row.id);
  IF jsonb_array_length(validation_result->'errors')>0 THEN
   RAISE EXCEPTION 'Invalid marketing lesson %: %',lesson_row.lesson_id,validation_result;
  END IF;
  IF validation_result->'warnings' IS DISTINCT FROM validation_before->'warnings' THEN
   RAISE EXCEPTION 'Marketing validation warnings changed for %',lesson_row.lesson_id;
  END IF;
  UPDATE public.academy_lesson_versions SET title=spec->>'title',objective=spec->>'objective',
   hook=spec->>'hook',change_note=release_name,validation=validation_result WHERE id=version_row.id;
 END LOOP;
 IF identities_before IS DISTINCT FROM {identity} THEN RAISE EXCEPTION 'Marketing lesson identity changed'; END IF;
 IF grading_before IS DISTINCT FROM {grading} THEN RAISE EXCEPTION 'Marketing grading identity changed'; END IF;
 IF outside_before IS DISTINCT FROM {outside} THEN RAISE EXCEPTION 'Content outside Marketing Basics modules 6–10 and six earlier lessons changed'; END IF;
 IF learner_before IS DISTINCT FROM {learner_fingerprint()} THEN
  RAISE EXCEPTION 'Learner records changed; abort marketing audit repairs';
 END IF;
 UPDATE public.academy_lesson_audit SET details=details||jsonb_build_object('publication_receipt',
  jsonb_build_object('release',release_name,'published_lessons',68,'archived_blocks',921,'changed_blocks',667,
   'learner_records_unchanged',true,'lesson_identity_unchanged',true,'grading_identity_unchanged',true,'outside_content_unchanged',true,
   'checked_tables',learner_before,'applied_at',clock_timestamp()))
 WHERE details->>'release'=release_name AND academy_lesson_id=(SELECT id FROM public.academy_lessons WHERE module_id='s03-m06' AND lesson_id='lm06-01');
END $mb610_release$;
"""
    MIGRATION.write_text(sql)
    print(f'Packaged {len(specs)} lessons / 667 changed blocks: {MIGRATION.name} ({len(sql)} characters)')


if __name__ == '__main__':
    build()
